# Generated by Django 4.2.10 on 2024-04-08 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='наименование')),
                ('slug', models.SlugField(max_length=150, unique=True, verbose_name='URl')),
                ('contents', models.TextField(verbose_name='содержание')),
                ('creation_date', models.DateField(auto_now_add=True, verbose_name='дата создания')),
                ('preview', models.ImageField(blank=True, null=True, upload_to='blog/', verbose_name='изображение')),
                ('published', models.DateField(verbose_name='дата публикации')),
                ('views_number', models.IntegerField(default=0, verbose_name='Количество просмотров')),
            ],
            options={
                'verbose_name': 'блог',
                'verbose_name_plural': 'блоги',
                'ordering': ('name',),
            },
        ),
    ]
